# Generated by Django 5.2.12 on 2026-03-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmartupAttendanceSync",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_from", models.CharField(max_length=10)),
                ("date_to", models.CharField(max_length=10)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("error", "Error")], default="pending", max_length=20)),
                ("report_title", models.CharField(blank=True, max_length=255)),
                ("html_report_path", models.CharField(blank=True, max_length=500)),
                ("run_url", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SmartupAttendanceRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("staff", models.CharField(max_length=255)),
                ("p", models.PositiveIntegerField(default=0)),
                ("pd", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sync", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rows", to="integrations.smartupattendancesync")),
            ],
            options={
                "ordering": ("staff",),
            },
        ),
    ]
